[package]
name = "number_range"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.152"
number_range = "0.3.2"

[lib]
name = "number_range"
crate-type = ["staticlib", "cdylib"]
